[general]
# EMPTY

[piecewalker]
# Find your Robot’s IP address
# https://niryorobotics.github.io/pyniryo/v1.2.1-1/setup/ip_address.html
robot_ip = "10.29.196.73"
# Height of the chips
chip_height = 0.0050 # 50.0 mm
# Fixed z-value that can optionally be used instead of calculating it via the averages during the calibration proccess
fixed_z = 0.0895

# Small Z offsets (meters)
pick_z_offset  =    -0.0015   # −2.0 mm for reliable pickup
place_z_offset =     0.0017   # +1.7 mm for gentle placement
#place_z_offset =     0.0005   # +0.5 mm for gentle placement

# Idle position the arm will move to between moves
[piecewalker.idle_pose]
x = 0.2005
y = -0.0157
z = 0.2993
#roll  = -2.179
#pitch = 1.461
#yaw   = -2.309
roll  = -2.860
pitch = 1.550
yaw   = -2.932


[piecewalker.grasp_params]
roll  = -2.860
pitch = 1.550
yaw   = -2.932
