[general]
used_fixed_z = true

[points]
corner_a = [0.147296, -0.109677, 0.089500]
corner_b = [0.154606, 0.106905, 0.089500]
corner_c = [0.365573, -0.124453, 0.089500]
unplaced_chips = [0.166961, -0.236066, 0.141011]
removed_chips = [0.246332, 0.210421, 0.084310]



